### ISSUE TITLE
Differences between `GET /api/v2/users/{id}/logs` and `GET /api/v2/logs`

### ISSUE THREAD

**Issue by chuyeow** [go-auth0/auth0#130]
I noticed that this client library does not implement the [`GET /api/v2/users/{id}/logs`](https://auth0.com/docs/api/management/v2#!/Users/get_logs_by_user) endpoint that returns log events for a single user.

Is this because I can use the [`GET /api/v2/logs`](https://auth0.com/docs/api/management/v2#!/Logs/get_logs) endpoint with `q=user_id:{id}` to get the exact same response?

The [API docs](https://auth0.com/docs/api/management/v2#!/) aren't super clear on why there could be 2 ways to do the same thing, and I'd like to confirm before I start using this library to get a user's log events, thank you!

**Comment by alexkappa** [comment]
Hi @chuyeow, I'm not sure myself if there are other differences other than what you mentioned. 

The idea is that the sdk should be aligned with the api as closely as possible. So if the functionality is missing, we should probably add it. 

Feel free to submit a PR if this functionality is important to you, otherwise I'll get to it at some point.

**Comment by alexkappa** [comment]
Closing this as the functionality seems to be available.
