### ISSUE TITLE
Auth0 added permissions to API v2

### ISSUE THREAD

**Issue by sinnedh** [go-auth0/auth0#57]
Similar to this issue https://github.com/go-auth0/auth0/issues/35 Auth0 has introduced permissions that are connected to roles. See
https://auth0.com/docs/api/management/v2#!/Roles/get_role_permission

If no-one else is working on this, I could offer to start implementing this.

**Comment by 23doors** [comment]
I also thought about adding it, it would be great to have it here and in terraform provieder. 
But apparently this project is kind of unmaintained or at very least in holiday mode. Added 1 field https://github.com/go-auth0/auth0/pull/54 to resource server that is required to enable RBAC and yet 18 days later, no response.

**Comment by alexkappa** [comment]
@sinnedh it would be great if you could give this a go 👍as with last time, I'm happy to assist.

@23doors the project is not unmaintained, but it certainly doesn't receive as much priority from me as I mainly work on it during the weekends. If you want to get your PR's approved faster, the tests are your friend. If they are green, it's easier for me to approve when on-the-go. Otherwise, I have to do some manual interventions to make it pass (in the case of #54 I had to rebase off the latest master).

**Comment by alexkappa** [comment]
The functionality is implemented as part of #37. Feel free to re-open if something is missing.
